services:
  db:
    image: postgres:latest
    container_name: tour_planner_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tour_planner
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
